auth0:
    audience: http://localhost:8080
    spring:
        security:
            oauth2:
                resourceserver:
                    jwt:
                        issuer_uri: https://dev-xwpvjc-f.auth0.com/